"""
Check signals that passed ATR filter on Oct 22
"""
import pandas as pd

# Just load the forecast parquet generated by 11_infer
forecast = pd.read_parquet('reports/intraday/2025-10-22/forecast_intraday.parquet')

print(f"Total signals in forecast: {len(forecast)}")

if len(forecast) == 0:
    print("\nNo signals generated. Let's check features file for high-prob signals...")
    df = pd.read_parquet('features/intraday/2025-10-22.parquet')
    
    # Load predictions file if exists
    import os
    pred_file = 'reports/intraday/2025-10-22/predictions_intraday.parquet'
    if os.path.exists(pred_file):
        preds = pd.read_parquet(pred_file)
        high_prob = preds[preds['prob_win'] >= 0.35].copy()
        print(f"\nSignals with prob >= 0.35: {len(high_prob)}")
        
        if len(high_prob) > 0:
            print("\nTop signals by prob_win:")
            print(high_prob.nlargest(10, 'prob_win')[['ticker', 'timestamp', 'prob_win', 'direction', 'spread_bps', 'ATR_pct', 'volume_ratio']].to_string())
            
            # Filter by whitelist
            whitelist = ['AMD', 'NVDA', 'TSLA', 'MSFT', 'AAPL', 'AMZN', 'META']
            white_sig = high_prob[high_prob['ticker'].isin(whitelist)]
            print(f"\nSignals in whitelist: {len(white_sig)}")
            
            # Filter LONG only
            long_sig = white_sig[white_sig['direction'] == 'LONG']
            print(f"LONG signals: {len(long_sig)}")
            
            if len(long_sig) > 0:
                print("\nLONG whitelist signals:")
                print(long_sig[['ticker', 'timestamp', 'prob_win', 'spread_bps', 'ATR_pct']].to_string())
                
                print(f"\nSpread distribution for LONG whitelist signals:")
                print(f"Min:    {long_sig['spread_bps'].min():.1f} bps")
                print(f"Median: {long_sig['spread_bps'].median():.1f} bps")
                print(f"Max:    {long_sig['spread_bps'].max():.1f} bps")
                
    else:
        print(f"Predictions file not found: {pred_file}")
